### ISSUE TITLE
ECU-C sometimes restart triggers, but never turns back on

### ISSUE THREAD

**Issue by gratjetost** [ksheumaker/homeassistant-apsystems_ecur#250] opened 2024-04-20 11:08 UTC
Im running 1.4.2 on a ECU-C with firmware 1.2.11
Sometimes a restart is triggered and the whole ECU-C breaks down. (no IP address, no access to dashboard)
Only option is to go there and turn it off and on again.
There is no reason why the restart triggers. 
In this example it just restarted in the middle of the day. 
Running in LAN cable, WIFI not enabled at all. 

![image](https://github.com/ksheumaker/homeassistant-apsystems_ecur/assets/11716629/3d1d2034-113f-405c-a5bc-60ff5a625656)
![image](https://github.com/ksheumaker/homeassistant-apsystems_ecur/assets/11716629/e7c8af4d-7114-4791-b8e7-549ea58acfc7)
![image](https://github.com/ksheumaker/homeassistant-apsystems_ecur/assets/11716629/e6dfb62f-4a61-4eb5-ba18-e8f76ebbbb19)

**Comment by HAEdwin** [comment] 2024-04-21 11:05
Please provide some info from the home-assistant.log. How often is the cache being used and what are the current integration settings (query interval, number of configured retries)? A restart is only initialized after the specified number of retries. If a good query occured the counter is being reset.

**Comment by HAEdwin** [comment] 2024-05-03 19:08
Sorry for the late response,.. you can specify random parameters for SSID and Password if connected by ethernet. Have you allready tried to reboot the ECU?

**Comment by HAEdwin** [comment] 2024-05-03 19:31
Does the ECU-C have an option to switch between WiFi and Ethernet? Could it be that you are able to connect using the WiFi connection after restart (when correct SSID and Password are applied) although ethernet is connected? It would mean that the ECU switched to WiFi operation and that somehow must be avoided.

**Comment by HAEdwin** [comment] 2024-05-03 19:47
It would be weird if neither a WLAN nor a LAN IP-address is assigned to the ECU. Have you looked at the DHCP table to see if the ECU received another IP-Address somehow? Is the MAC still the same for both WLAN and LAN interface on the ECU?

**Comment by HAEdwin** [comment] 2024-05-03 19:57
If you encounter the issue of the cache being used very often, try to replace the ECU or externa antennas if possible. Sometimes bringing them too close to WiFi AP's causes interference because 2.4Ghz WiFi and Zigbee share the same 2.4Ghz band.
Last option would be to change the "215" value on line 87 of __init__.py into a random value like "111" to prevent the integration from rebooting the ECU. You could then use a smartplug to reboot the ECU using a HA automation.

**Comment by HAEdwin** [comment] 2024-06-23 14:51
It's in __init__.py If it does not work for the ECU-C you can bypass it there. It is compatible with the ECU-R pro and I think someone with an ECU-C also had positive results but might have changed because of a firmware update.

**Comment by HAEdwin** [comment] 2024-06-24 07:21
There is no reboot function indeed. Some users noticed that, when you change the WiFi settings, the ECU will automatically initiate a reboot. This is the trick used. The 215 to 115 change you made earlier prevents calling this method so the ECU-C will not lock up anymore. Only thing to do now is to start the integration again at let's say 04:00 by switching ECU Query Device back on and see if the ECU will accept queries again. But a possible alternative to this integration is almost available. If you are also running Pi-Hole, AdGuard or others ways to rewrite DNS traffic you can test that new integration. As with the current integration it was written with only the ECU-R in hand, same goes for the new solution. If we had all ECUs in our possession, it would be easier to test compatibility or adjust the integration so that all models can be supported.

**Comment by ddaddy** [comment] 2024-07-01 12:27
My ECU-C also went off last night and never came back on.
The HA logs show several comms issues, so I don't think the ECU-C was to blame.
It even shows that the attempt to restart it failed
```
Attempt to restart ECU failed with error: HTTPConnectionPool(host='192.168.2.15', port=80): Max retries exceeded with url: /index.php/management/set_wlan_ap (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4d958740>: Failed to establish a new connection: [Errno 113] Host is unreachable')). Querying is stopped automatically.
```
The strange thing is that it was very difficult to get it to reconnect to my network.

I switched it off and on many times, but it either wouldn't connect or my router wouldn't give it an IP.
Pressing the AP button did nothing also, I could not connect to it locally.
The only thing that got it working again, was pressing the reset button, which eventually brought up the local access wifi and I connected and reset the wifi connection.

**Comment by ddaddy** [comment] 2024-07-01 13:31
Just looking through the code to reboot the device. I see you set `channel` to `0` but the web interface only offers `1-13`. I wonder if setting channel to 0 is causing the re-connection issues?

Also, the web interface also sends the `ip` param with a default of `172.30.1.1` but you don't send this parameter.

**Comment by HAEdwin** [comment] 2024-07-02 08:35
Sorry I do not own an ECU-C so I'm unable to test. You can try and alter it in the code or just try a post to the ECU with the possibly correct parameters like so: http://[ip-adress]/index.php/management/set_wlan_ap?SSID: [my ssid], 'channel': [my channel], 'method': 2, 'psk_wep': '', 'psk_wpa': [my wifi password]

**Comment by ddaddy** [comment] 2024-07-02 11:59
I'm not sure why I even looked into the reboot code as [my first post](https://github.com/ksheumaker/homeassistant-apsystems_ecur/issues/250#issuecomment-2200013322) clearly shows it couldn't reboot the ECU due to a comms issue.
So the issues must lie within the ECU.

**Comment by ddaddy** [comment] 2024-07-02 13:22
I can see from the html `Form` elements that it sends a valid number between 1-13 for the channel (Default 6) and the `ip` parameter with default of `172.30.1.1`.
I'm not sure if they are actually required in the `POST`, but they are there to be sent in the HTML so no harm in adding them in.

This was the first time in a long time my ECU went down, so i'll monitor it and get more logs if it happens again.
I do just think that something happened with either my router, ecu or RPi that made several things unreachable. When it all came back online, the ECU just wouldn't connect to my network. So the reboot command was pointless as the IP was unreachable.

**Comment by ddaddy** [comment] 2024-07-03 08:45
@gratjetost That is exactly what it is using. It is setting the local access which in turns reboots the ECU.

I've just proxied the requests, and it seems the IP isn't sent, however I would change the channel from 0 to 6 on line 84

`SSID=ECU-WIFI_2465&channel=6&method=0&psk_wep=&psk_wpa=`

**Comment by ddaddy** [comment] 2024-07-03 21:22
I think you’re mistaken. The WLAN and LWA aren’t 2 options of one or the other. WLAN is a tab that lets you set which WiFi to connect to, and LWA sets the local WiFi you can connect to on the ECU.
They’re independent of each other.
When you save the LWA settings, it reboots the ECU.

**Comment by ddaddy** [comment] 2024-07-03 21:40
You’re not selecting one or the other!
The web interface has 2 tabs. One sets the WiFi settings that the ECU connects to, and the other sets the local wireless settings.
Both are valid.

**Comment by Dakhaasje** [comment] 2024-08-06 11:55
In my humble opinion: zigbee, bluetooth and Wifi use all 2.4 ghz. Zigbee is very sensitive to interference to any electronics nearby. My advice is to keep zigbee appliances at least 40cm away from other electronics.

**Comment by HAEdwin** [comment] 2024-08-21 09:03
You might want to try this as an alternative: https://github.com/HAEdwin/homeassistant-apsystems_ecu_proxy

**Comment by HAEdwin** [comment] 2024-08-21 19:04
The proxy IP dialog can be omitted, it is not used yet. If you ping ecu.apsystemsema.com on the LAN you should get a reply on 192.168.1.200 if that is correct you could enable the debug mode in the integration to see what happens.
![image](https://github.com/user-attachments/assets/c4fe7c70-f2e7-4698-bfc1-faaefb595733)
If inverters are down you should wait for the next day to have entities created. Some messages are also ignored because they provide no current data but old correction data for the EMA site.

**Comment by HAEdwin** [comment] 2024-08-21 19:12
In that case you could leave it running and discover the entities when the Inverters are online. That should happen automatically for each inverter. Debug log should show info allthough inverters are down.

**Comment by HAEdwin** [comment] 2024-08-21 19:17
The download button becomes available when you stop debug logging. You could also install the File Editor Add-on to view the home-assistant.log file.

**Comment by HAEdwin** [comment] 2024-08-21 19:26
When inverters are down the interval drops to once every 10 - 15 minutes. But you should see messages like: Received message type from ECU ignored for further processing

**Comment by HAEdwin** [comment] 2024-08-21 19:50
Better wait until tomorrow

**Comment by HAEdwin** [comment] 2024-08-22 07:47
If you check const.py make sure: SEND_TO_EMA = True and EMA_HOST = "3.67.1.32" and let's continue in my repository because this is off-topic in for this integration. Please create an issue there, hope I can solve it if it still remains to be an issue.

**Closed by HAEdwin** 2024-08-22 07:47 UTC
Labels: ECU-C

**Comment by hallard** [comment] 2025-03-05 23:02
Hi, Sorry to hijack this issue but got an ECU-C with same issue, restart just get ECU-C stop responding until I power cycle the device. Could makes sense since if it can't get answer after 5 retries (because it is crashed), it may not able to respond to "reboot" query.
I'm wondering if we could use another approach, I mean not waiting crash, but having a power cycle button that we can trigger at defined time with an automation. Worth trying this before connecting ECU-C to shelly to power cycle this poor device.

**Comment by Dakhaasje** [comment] 2025-03-06 15:17
The problem is not quite clear to me. 
As I understand, your ecu-c gateway stops responding ,even in Ecu app/website. 
How is this related to HA? or the Api?
Seems to me your Ecu-c is at fault.
If you want the Ecu-C to reboot every hour or so, connect the power supply to some Tuya or Tasmota outlet socket and program a schedule. You can even make an automation that regularly checks the Ecu-C availability and let the socket power cycle when offline.

**Comment by hallard** [comment] 2025-03-06 16:02
Sorry, I was just saying that sometimes when this HA plugins try to restart ECU-C (because of 5 failed read attempts), it just initiate the restart but never get back to life and I need to power cycle ECU-C.
What I mean is if this HA plug ins is able to trigger a ECU-C restart on 5 consecutive failed read attempt it could be possible to trigger ECU C restart on time schedule with automation?

Because my assumption is that if ECU-C failed 5 consecutive HTTP read it may be already crashed and trigger a restart will have no effect because it is not responding to HTTP queries.

**Comment by HAEdwin** [comment] 2025-03-07 07:46
@hallard @gratjetost  I will continue further development on my git at https://github.com/HAEdwin/homeassistant-apsystems_ecu_reader 

You all might want to try this version and post feature wishes like a power cycle button into the discussions section.
